[project]
name = "qc-lightgbm"
version = "0.1.0"
description = ""
authors = []
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64"]

[tasks]

[dependencies]
python = ">=3.8"
pip = ">=24.0"

