context:
  version: "0.1.0"

package:
  name: qc-lightgbm
  version: ${{ version }}

source:
  git: https://github.com/neNasko1/LightGBM.git

requirements:
  build:
    - ${{ compiler('cxx') }}
    - python>=3.11
    - pip
    - cmake
    - python-build>=0.10
    - scikit-learn
    - scikit-build-core
  host:
    - python>=3.11
    - pip
    - scikit-learn
  run:
    - python>=3.11
    - pip
    - scikit-learn

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: ""
  summary: ""
