context:
  version: "4.5.100"

package:
  name: lightgbm
  version: ${{ version }}

source:
  path: "../"

requirements:
  build:
    - python>=3.11
    - pip
    - cmake
    - python-build>=0.10
    - scikit-learn
    - scikit-build-core
    - ${{ compiler('cxx') }}

  host:
    - python>=3.11
    - pip
    - cmake
    - python-build>=0.10
    - scikit-learn
    - scikit-build-core
    - ${{ compiler('cxx') }}

  run:
    - python>=3.11
    - pip
    - scikit-learn

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: ""
  summary: ""
