context:
  version: "4.5.100"

package:
  name: lightgbm
  version: ${{ version }}

source:
  path: "../"

requirements:
  build:
    - python
    - pip
    - cmake>=3.18
    - python-build>=0.10
    - scikit-build-core
    - ${{ compiler('cxx') }}
    - if: linux
      then:
        - libstdcxx-ng<=12.0

  run:
    - python
    - pip
    - scikit-learn

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: ""
  summary: ""
